create table accounts
(
    id         bigint generated by default as identity primary key,
    owner_name varchar     not null,
    balance    bigint      not null check (balance >= 0),
    created_at timestamptz not null
);

create table transfers
(
    id              bigint generated by default as identity primary key,
    amount          bigint      not null check (amount > 0),
    from_account_id bigint      not null,
    to_account_id   bigint      not null,
    created_at      timestamptz not null,
    constraint fk_transfers_from_account foreign key (from_account_id) references accounts (id),
    constraint fk_transfers_to_account foreign key (to_account_id) references accounts (id)
);

create table idempotency_keys
(
    key         varchar primary key,
    transfer_id bigint,
    created_at  timestamptz not null,
    constraint fk_idempotency_keys_transfer foreign key (transfer_id) references transfers (id)
);

CREATE INDEX idx_transfers_from_account_id ON transfers USING btree (from_account_id);

CREATE INDEX idx_transfers_to_account_id ON transfers USING btree (to_account_id);
